#!/bin/sh 
#/etc/init.d/my-ai-agent 
### BEGIN INIT INFO 
# Provides:my-ai-agent 
# Required-Start:$remote_fs $syslog 
# Required-Stop:$remote_fs $syslog 
# Default-Start:2 3 4 5 
# Default-Stop:0 1 6 
# Short-Description: my-ai-agent 
# Description: This service is used to start my-ai-agent 
### END INIT INFO 
case "$1" in      
start)      
    echo "start my-ai-agent."      
    nohup /home/szlfw/raspizerow/my-ai-agent &    
    ;;      
stop)      
    echo "stop my-ai-agent."      
    killall my-ai-agent
    ;;      
*)      
    echo "Usage: service my-ai-agent start|stop"      
    exit 1      
    ;; 
esac 
exit 0 